server:
  port: 8081

keycloak:
  url: http://localhost:8180
  realm: my-bank-realm
  transfer:
    secret: secret
consul:
  host: localhost
  port: 8500

spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
      client:
        registration:
          transfer-service:
            client-id: transfer-service
            client-secret: ${keycloak.transfer.secret}
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        prefer-ip-address: true