server:
  port: 8081

keycloak:
  url: http://localhost:8180
  realm: my-bank-realm
  transfer:
    secret: secret

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:my_bank_transfer}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
      client:
        registration:
          transfer-service:
            client-id: transfer-service
            client-secret: ${keycloak.transfer.secret}
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
  kafka:
    bootstrap-servers: localhost:9001
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        interceptor.classes: io.opentelemetry.instrumentation.kafkaclients.v2_6.TracingProducerInterceptor
    template:
      observation-enabled: true

resilience4j:
  circuitbreaker:
    instances:
      accounts-service:
        slidingWindowSize: 10
        failureRateThreshold: 3
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1
        ignore-exceptions:
          - com.github.dgaponov99.practicum.mybank.transfer.exception.ExternalMultipleException

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1
    propagation:
      type: w3c

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name}