{
 "title": "Business",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transfer Per Minute (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(notification_total[2m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(notification_failed_total[2m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(notification_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notication Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(notification_failed_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Transfer Per Minute (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(transfer_total[2m]) * 60", "legendFormat": "__auto" },
    {
     "expr": "rate(transfer_failed_total[2m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(transfer_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(transfer_failed_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cash Withdraw", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cash Withdraw Per Minute (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(cash_withdraw_total[2m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cash_withdraw_failed_total[2m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cash Withdraw Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cash_withdraw_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cash Withdraw Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cash_withdraw_failed_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cash Deposit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cash Deposit Per Minute (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(cash_deposit_total[2m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cash_deposit_failed_total[2m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cash Deposit Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cash_deposit_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cash Deposit Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cash_deposit_failed_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}