{
 "title": "Spring Boot Http (3.x)",
 "description": "This dashboard provides real-time monitoring of HTTP requests in a Spring Boot application. It uses Spring Boot Actuator to expose metrics, Prometheus for data collection, and Grafana for visualization.",
 "tags": [ "http" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum,application)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum{application=\"$application\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum{application=~\"$application\", cluster=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Average Request Count (2m)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2xx Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"2..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"4..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"5..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Average Latency (5m)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "2xx Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"2..\"}[2m]) / irate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"2..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"4..\"}[2m]) / irate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"4..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"5..\"}[2m]) / irate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"5..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Percentile Latency (5m)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum(\r\n    rate(http_server_requests_seconds_bucket{\r\n      application=\"$application\",\r\n      cluster=~\"$cluster\",\r\n      instance=~\"$instance\"\r\n    }[2m])\r\n  ) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(\r\n    rate(http_server_requests_seconds_bucket{\r\n      application=\"$application\",\r\n      cluster=~\"$cluster\",\r\n      instance=~\"$instance\"\r\n    }[2m])\r\n  ) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\r\n  sum(\r\n    rate(http_server_requests_seconds_bucket{\r\n      application=\"$application\",\r\n      cluster=~\"$cluster\",\r\n      instance=~\"$instance\"\r\n    }[2m])\r\n  ) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}