services:
  keycloak:
    container_name: bank-keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    ports:
      - "8180:8080"
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { java.net.URI uri = java.net.URI.create(args[0]); System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)uri.toURL().openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/health/live' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8200/v1/sys/health" ]
      interval: 2s
      timeout: 2s
      retries: 10
    restart: unless-stopped

  vault-init:
    image: hashicorp/vault:1.15
    container_name: vault-init
    depends_on:
      vault:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env:ro
      - ./vault/vault-init.sh:/app/vault-init.sh
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    entrypoint: [ "/bin/sh", "/app/vault-init.sh" ]
    restart: no
