server:
  port: 8084

keycloak:
  url: http://auth-local:8180
  realm: my-bank-realm

spring:
  application:
    name: notifications-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
