server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9001
    consumer:
      group-id: notifications-service
      enable-auto-commit: false
      isolation-level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: com.github.dgaponov99.practicum.mybank.notifications.dto
    listener:
      ack-mode: manual

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
