server:
  port: 8083

spring:
  application:
    name: my-bank-cach
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/my-bank-realm
      client:
        registration:
          cach-service:
            client-id: cach-service
            client-secret: LO9KIdXJZpqYMrSMZZz5VOdUVnnauorb
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/my-bank-realm
