server:
  port: 80

spring:
  application:
    name: frontend-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: frontend-service
            client-secret: ${KEYCLOAK_FRONTEND_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
