server:
  port: 80

keycloak:
  url: http://auth-local:8180
  realm: my-bank-realm
  frontend:
    secret: secret

spring:
  application:
    name: frontend-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: frontend-service
            client-secret: ${keycloak.frontend.secret}
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1