input {
  kafka {
    bootstrap_servers => "broker-0-kafka-local:9092"
    topics => ["app-logs"]
    group_id => "logstash-elk-group"

    codec => json
  }
}

filter {
  if [log][logger] =~ /activemq/ or [log][logger] =~ /org\.apache\.kafka/ {
    drop { }
  }

  if ![service][name] {
    mutate {
      add_field => {
        "[service][name]" => "unknown_service"
      }
    }
  }

  mutate {
    remove_field => [
      "stream",
      "logtag"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "monitoring-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}