input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] =~ "activemq" or [logger_name] =~ "org.apache.kafka" {
    drop { }
  }

  if ![service_name] {
    mutate {
      add_field => { "service_name" => "unknown_service" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "monitoring-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}