apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ include "frontend-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: {{ .Values.keycloak.secret.property }}
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: client-secret
            - name: GATEWAY_SERVICE_URL
              value: {{ .Values.gateway.service.url }}
            - name: ZIPKIN_HOST
              value: {{ .Values.zipkin.host }}
