apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: app
        property: {{ .Values.keycloak.secret.property }}