apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notifications-chart.name" . }}
  labels:
    {{ include "notifications-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
            - name: ZIPKIN_HOST
              value: {{ .Values.zipkin.host }}
