apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifications-chart.name" . }}
  labels:
    {{ include "notifications-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{ include "notifications-chart.selectorLabels" . | nindent 4 }}
