{{- range $name, $comp := .Values.components }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-keycloak-secret" $name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ printf "%s-keycloak-secret" $name }}
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: app
        property: {{ $comp.keycloak.secret.property }}
---
{{- end }}