{{- range $name, $comp := .Values.components }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $comp.service.port }}
      targetPort: {{ $comp.service.port }}
  selector:
    app: {{ $name }}
---
{{- end }}